# Generated by Django 5.2 on 2026-05-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='doctor',
            name='examination_type',
            field=models.CharField(choices=[('time_share', 'تقاسم الوقت'), ('percentage', 'نسبة مئوية')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='percentage_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
