# Generated by Django 5.2 on 2026-05-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_receptionist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='examination_type',
            field=models.CharField(blank=True, choices=[('time_share', 'تقاسم الوقت'), ('percentage', 'نسبة مئوية')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
