# Generated by Django 5.2 on 2026-05-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_doctor_examination_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='price_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
