# Generated by Django 5.2 on 2026-06-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_updated_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='clinic_percentage',
            new_name='clinic_money',
        ),
        migrations.AddField(
            model_name='service',
            name='doctor_money',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
