# Generated by Django 5.2 on 2026-06-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_clinic_percentage_service_clinic_money_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerecord',
            old_name='clinic_amount',
            new_name='clinic_money',
        ),
        migrations.RenameField(
            model_name='servicerecord',
            old_name='doctor_amount',
            new_name='doctor_money',
        ),
        migrations.RemoveField(
            model_name='service',
            name='clinic_money',
        ),
        migrations.RemoveField(
            model_name='service',
            name='doctor_money',
        ),
    ]
