# Generated by Django 5.2 on 2026-06-05 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0006_appointment_type'),
        ('patients', '0003_alter_patient_birth_date'),
        ('services', '0004_rename_clinic_amount_servicerecord_clinic_money_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('appointment', 'موعد'), ('service', 'خدمة')], max_length=20, verbose_name='نوع الخصم')),
                ('original_amount', models.FloatField(verbose_name='المبلغ الأصلي')),
                ('discount_amount', models.FloatField(verbose_name='قيمة الخصم')),
                ('final_amount', models.FloatField(verbose_name='المبلغ بعد الخصم')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='سبب الخصم')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='appointments.appointment', verbose_name='الموعد')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts_created', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='patients.patient', verbose_name='المريض')),
                ('service_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='services.servicerecord', verbose_name='سجل الخدمة')),
            ],
            options={
                'verbose_name': 'سجل خصم',
                'verbose_name_plural': 'سجلات الخصومات',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rent', 'إيجار'), ('salaries', 'رواتب'), ('supplies', 'مستلزمات'), ('utilities', 'مرافق'), ('maintenance', 'صيانة'), ('marketing', 'تسويق'), ('other', 'أخرى')], max_length=20, verbose_name='التصنيف')),
                ('description', models.CharField(max_length=255, verbose_name='الوصف')),
                ('amount', models.FloatField(verbose_name='المبلغ (ج.م)')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_created', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
