# Generated by Django 5.2 on 2026-09-14 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_type'),
        ('dashboard', '0001_initial'),
        ('patients', '0003_alter_patient_birth_date'),
        ('services', '0004_rename_clinic_amount_servicerecord_clinic_money_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountrecord',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='discountrecord',
            name='source',
            field=models.CharField(choices=[('clinic', 'من نصيب العيادة'), ('doctor', 'من نصيب الطبيب')], default='clinic', max_length=20),
        ),
        migrations.AlterField(
            model_name='discountrecord',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='discountrecord',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discountrecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='discountrecord',
            name='discount_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='discountrecord',
            name='discount_type',
            field=models.CharField(choices=[('appointment', 'موعد'), ('service', 'خدمة')], max_length=20),
        ),
        migrations.AlterField(
            model_name='discountrecord',
            name='final_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='discountrecord',
            name='original_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='discountrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='discountrecord',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discountrecord',
            name='service_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='services.servicerecord'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('rent', 'إيجار'), ('salaries', 'رواتب'), ('supplies', 'مستلزمات'), ('utilities', 'مرافق'), ('maintenance', 'صيانة'), ('marketing', 'تسويق'), ('other', 'أخرى')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
