# Generated by Django 5.2 on 2026-05-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'انثى')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير'), ('doctor', 'دكتور'), ('receptionist', 'استقبال'), ('patient', 'مريض')], default='patient', max_length=14),
        ),
    ]
