# Generated by Django 5.2 on 2026-05-04 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.IntegerField()),
                ('dosage_unit', models.CharField(choices=[('tablet', 'قرص'), ('capsule', 'كبسولة'), ('injection', 'حقنة'), ('syrup', 'شراب')], max_length=20)),
                ('frequency', models.CharField(choices=[('as_needed', 'عند الحاجة'), ('once_daily', 'مرة يومياً'), ('twice_daily', 'مرتين يومياً'), ('thrice_daily', 'ثلاث مرات يومياً'), ('four_times_daily', 'اربع مرات يومياً'), ('five_times_daily', 'خمس مرات يومياً'), ('six_times_weekly', 'ست مرات اسبوعياً'), ('every_8_hours', 'كل 8 ساعات'), ('every_12_hours', 'كل 12 ساعة'), ('every_24_hours', 'كل 24 ساعة')], max_length=20)),
                ('duration', models.IntegerField()),
                ('duration_unit', models.CharField(choices=[('days', 'أيام'), ('weeks', 'أسابيع'), ('months', 'أشهر'), ('years', 'سنوات')], max_length=20)),
                ('route', models.CharField(choices=[('oral', 'فموي'), ('topical', 'موضعي'), ('inhalation', 'استنشاق'), ('injection', 'حقن'), ('rectal', 'شرجي'), ('vaginal', 'مهبلي'), ('ophthalmic', 'قطرات عيون'), ('otic', 'قطرات أذن'), ('nasal', 'بخاخ أنف'), ('sublingual', 'تحت اللسان'), ('transdermal', 'عبر الجلد'), ('intravenous', 'وريدي'), ('intramuscular', 'عضلي'), ('subcutaneous', 'تحت الجلد')], max_length=20)),
                ('notes', models.CharField(blank=True, choices=[('take_with_food', 'تناول مع الطعام'), ('take_on_empty_stomach', 'تناول على معدة فارغة'), ('before_sleep', 'قبل النوم'), ('after_waking', 'بعد الاستيقاظ'), ('with_meals', 'مع الوجبات'), ('between_meals', 'بين الوجبات'), ('before_meals', 'قبل الوجبات'), ('after_meals', 'بعد الوجبات'), ('after_breakfast', 'بعد الفطور'), ('after_lunch', 'بعد الغداء'), ('after_dinner', 'بعد العشاء')], max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_items', to='appointments.appointment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_items_created', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_items', to='medicines.medicine')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_items_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
