# Generated by Django 5.2 on 2026-05-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_prescriptionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='session_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
