# Generated by Django 5.2 on 2026-05-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_session_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='room_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
