# Generated by Django 5.2 on 2026-06-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinic_money',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_money',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='dosage_unit',
            field=models.CharField(choices=[('tablet', 'قرص'), ('capsule', 'كبسولة'), ('injection', 'حقنة'), ('syrup', 'شراب'), ('pill', 'حبة')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='notes',
            field=models.CharField(blank=True, choices=[('take_with_food', 'تناول مع الطعام'), ('take_on_empty_stomach', 'تناول على معدة فارغة'), ('before_sleep', 'قبل النوم'), ('after_waking', 'بعد الاستيقاظ'), ('with_meals', 'مع الوجبات'), ('between_meals', 'بين الوجبات'), ('before_meals', 'قبل الوجبات'), ('after_meals', 'بعد الوجبات'), ('after_breakfast', 'بعد الفطور'), ('after_lunch', 'بعد الغداء'), ('after_dinner', 'بعد العشاء'), ('after_food', 'بعد الطعام')], max_length=25, null=True),
        ),
    ]
