# Generated by Django 5.2 on 2026-06-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_clinic_money_appointment_doctor_money_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('examination', 'كشف'), ('follow_up', 'متابعة')], default='examination', max_length=20),
        ),
    ]
