# Generated by Django 5.2 on 2026-10-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='room_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
