# Generated by Django 5.2 on 2026-05-04 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200)),
                ('concentration', models.IntegerField(blank=True, null=True)),
                ('concentration_unit', models.CharField(choices=[('mg', 'ملجم'), ('mcg', 'مكجم'), ('mg/ml', 'ملجم/مل'), ('mcg/ml', 'مكجم/مل')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
